id: P010314
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1GS49280
  title: གསོ་རིག་སྨན་གྱི་རོ་ནུས་ངོས་འཛིན་གསལ་སྟོན་ཕྱོགས་སྒྲིག་རིན་ཆེན་སྒྲོན་མེ
  author: ''
  volumes:
    9ce86c55b6cd449aa32c7553c7bafdda:
      image_group_id: I1PD34006
      title: ''
      volume_number: 1
      total_pages: 476
      base_file: v001.txt
